### ISSUE TITLE
Steam is not installed

### ISSUE THREAD

**Issue by MarqBruh** [p2r3/spplice#6] opened 2022-09-28 08:44 UTC
Says steam is not installed when I try to install a mod, I have it on my D drive and I don't see a way to change the directory.

**Comment by p2r3** [comment] 2022-09-28 18:06
Spplice gets the installation directory of Steam from the Windows registry. Perhaps that is somehow misconfigured?

What is the output of `reg query HKCU\SOFTWARE\Valve\Steam /v SteamPath` when run in `cmd.exe`?

**Comment by MarqBruh** [comment] 2022-09-29 09:29
cmd doesn't seem to recognize reg as a command.
![image](https://user-images.githubusercontent.com/78675172/192995493-b9f4725e-872f-466d-a209-9dd20254d605.png)

**Comment by p2r3** [comment] 2022-09-30 23:44
What Windows version is this?

**Comment by MarqBruh** [comment] 2022-10-03 04:53
Windows 10

**Comment by PancakeTAS** [comment] 2022-10-12 14:44
Interesting, it looks like "C:\Windows\System32\" is not part of your path. Can you show us your PATH Environment Variable? Run `echo %PATH%` in `cmd.exe`.

As a workaround on spplice's side, you could change `reg query` to `C:\Windows\System32\reg.exe query` as that's where reg.exe is located.

**Comment by p2r3** [comment] 2022-10-12 15:11
That does seem to be the issue, and @MCPfannkuchenYT's proposed workaround is what Spplice is going to take, unless setting PATH from Neutralino proves to be simpler. Haven't gotten around to it yet.

On a slightly less related note, this might as well have been the cause for lots of earlier issues with `taskkill` hanging on some systems. Though I would have expected this issue to be more prevalent.

**Comment by p2r3** [comment] 2022-11-10 11:32
The underlying problem has been tended to in 3b7212d2c00ae4a65d9a999eea36e101893e7d7e. Therefore I am closing this thread. If the problem persists after the next release, please open a new issue.

**Closed as completed by p2r3** 2022-11-10 11:32 UTC
